org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Minecraft and loaders
minecraft_version=26.2
loader_version=0.19.5
neoforge_version=26.2.0.88
architectury_api_version=21.1.11
enabled_platforms=fabric,neoforge

# Mod Properties
mod_version=9.0.0-alpha.7
maven_group=cn.pupperclient
archives_base_name=Pupper Client
modrinth_project_id=pupper-client

# Dependencies
fabric_api_version=0.161.0+26.2
